image: golang:1.11

variables:
    PROJECT_NAME: github.com/sagikazarmark/modern-go-application
    DOCKER_IMAGE: registry.gitlab.com/${CI_PROJECT_PATH}

stages:
    - dependencies
    - test
    - build
    - packaging

before_script:
    # Create a symbolic link under $GOPATH
    - cd $GOPATH/src
    - mkdir -p $(dirname $PROJECT_NAME)
    - ln -s $CI_PROJECT_DIR $PROJECT_NAME
    - cd $PROJECT_NAME
    - pwd

cache:
    key: vendor
    paths:
        - vendor/

dependencies:
    stage: dependencies
    script:
        - make vendor

test:
    stage: test
    script:
        - make test
    artifacts:
        reports:
            junit: build/test_results/main/results.xml

test-integration:
    stage: test
    script:
        - make test-integration
    artifacts:
        reports:
            junit: build/test_results/integration/results.xml

lint:
    stage: test
    script:
        - make lint

.build: &build_definition
    stage: build
    script:
        - export CI_BUILD_DATE=$(date +%FT%T%z)
        - make build-release VERSION=${CI_COMMIT_REF_NAME} COMMIT_HASH=${CI_COMMIT_SHA} BUILD_DATE=${CI_BUILD_DATE}
        - make build-debug VERSION=${CI_COMMIT_REF_NAME} COMMIT_HASH=${CI_COMMIT_SHA} BUILD_DATE=${CI_BUILD_DATE}

snapshot:
    <<: *build_definition
    only:
        - master
    artifacts:
        paths:
            - build/
        expire_in: 2 days

release:
    <<: *build_definition
    only:
        - tags
    artifacts:
        paths:
            - build/

.docker: &docker_definition
    stage: packaging
    image: docker:stable
    variables: &docker_definition_variables
        DOCKER_HOST: tcp://docker:2375/
        DOCKER_DRIVER: overlay2
        DOCKER_TAG: ${CI_COMMIT_REF_NAME}
    services:
        - docker:dind
    before_script:
        - docker info
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
        - apk add --update --no-cache ca-certificates make
    script: make docker docker-debug

docker:snapshot:
    <<: *docker_definition
    dependencies:
        - snapshot
    only:
        - master

docker:release:
    <<: *docker_definition
    variables:
        <<: *docker_definition_variables
        DOCKER_LATEST: 1
    dependencies:
        - release
    only:
        - tags
    script: make docker docker-debug
