image: golang:1.11

variables:
    PROJECT_NAME: github.com/sagikazarmark/modern-go-application

stages:
    - dependencies
    - test
    - build
    - packaging

before_script:
    # Create a symbolic link under $GOPATH
    - cd $GOPATH/src
    - mkdir -p $(dirname $PROJECT_NAME)
    - ln -s $CI_PROJECT_DIR $PROJECT_NAME
    - cd $PROJECT_NAME
    - pwd

cache:
    key: vendor
    paths:
        - vendor/

dependencies:
    stage: dependencies
    script:
        - make vendor

test:
    stage: test
    script:
        - make test

lint:
    stage: test
    script:
        - make lint

.build: &build_definition
    stage: build
    script:
        - make build-release build-debug VERSION=${CI_COMMIT_REF_NAME} COMMIT_HASH=${CI_COMMIT_SHA} BUILD_DATE="$(date)"

snapshot:
    <<: *build_definition
    only:
        - master
    artifacts:
        paths:
            - build/
        expire_in: 2 days

release:
    <<: *build_definition
    only:
        - tags
    artifacts:
        paths:
            - build/

.docker: &docker_definition
    stage: packaging
    before_script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    script:
        - docker build --build-arg BUILD_DIR=build --build-arg BINARY_NAME=$(make var-BINARY_NAME) -t registry.${PROJECT_NAME}:${CI_COMMIT_REF_NAME} -f Dockerfile.local .
        - docker build --build-arg BUILD_DIR=build --build-arg BINARY_NAME=$(make var-BINARY_NAME)-debug -t registry.${PROJECT_NAME}:${CI_COMMIT_REF_NAME}-debug -f Dockerfile.debug .
        - docker push registry.${PROJECT_NAME}:${CI_COMMIT_REF_NAME}
        - docker push registry.${PROJECT_NAME}:${CI_COMMIT_REF_NAME}-debug

docker:snapshot:
    <<: *docker_definition
    dependencies:
        - snapshot
    only:
        - master

docker:release:
    <<: *docker_definition
    dependencies:
        - release
    only:
        - tags
    script:
        - docker tag registry.${PROJECT_NAME}:${CI_COMMIT_REF_NAME} registry.${PROJECT_NAME}:latest
        - docker tag registry.${PROJECT_NAME}:${CI_COMMIT_REF_NAME}-debug registry.${PROJECT_NAME}:latest-debug
        - docker push registry.${PROJECT_NAME}:latest
        - docker push registry.${PROJECT_NAME}:latest-debug
