version: "2.1"

services:
    db:
        image: mysql:5.7
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: database

    jaeger:
        image: jaegertracing/all-in-one:latest
        environment:
            COLLECTOR_ZIPKIN_HTTP_PORT: 9411
