version: 2

jobs:
    build:
        docker:
            -
                image: circleci/golang:1.11

        working_directory: /go/src/github.com/sagikazarmark/modern-go-application

        steps:
            - checkout

            -
                restore_cache:
                    name: Restore build dependencies
                    keys:
                        - build-deps-v1-{{ .Branch }}-{{ checksum "Makefile" }}

            -
                restore_cache:
                    name: Restore dependencies
                    keys:
                        - gopkg-v1-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
                        - gopkg-v1-{{ .Branch }}
                        - gopkg-v1-master
                        - gopkg-v1

            -
                run:
                    name: Install dependencies
                    command: make vendor

            -
                save_cache:
                    name: Save dependencies
                    key: gopkg-v1-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
                    paths:
                        - vendor/

            -
                run:
                    name: Run tests
                    command: make test
                    environment:
                        VERBOSE: 1

            -
                save_cache:
                    name: Save build dependencies
                    key: build-deps-v1-{{ .Branch }}-{{ checksum "Makefile" }}
                    paths:
                        - bin/
