openapi: 3.0.1
info:
  description: Some description
  title: Hello World API
  version: 1.0.0
servers:
- url: https://api.hello.world/
- url: http://api.hello.world/
paths:
  /greeting/sayHello:
    post:
      operationId: sayHello
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HelloRequest'
          application/xml:
            schema:
              $ref: '#/components/schemas/HelloRequest'
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/HelloResponse'
          description: successful operation
      summary: SayHello says hello to someone
components:
  schemas:
    HelloResponse:
      example:
        reply: reply
      properties:
        reply:
          type: string
      type: object
    HelloRequest:
      example:
        name: name
      properties:
        name:
          type: string
      type: object
  securitySchemes:
    api_key:
      in: header
      name: api_key
      type: apiKey
