---
-
    name: Gather user facts
    set_fact:
        user: "{{ ansible_local.mga_user }}"

-
    name: Copy application binary
    copy:
        src: "{{ binary_source }}/{{ binary_name }}"
        dest: "{{ user.home }}/bin/modern-go-application"
        backup: true
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
        mode: 0700
    notify: restart application
