---
-
    name: Create application configuration
    template:
        src: config.toml
        dest: "{{ user.home }}/etc/{{ mga_service_name }}.toml"
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
        mode: 0600

-
    name: Create systemd configuration
    template:
        src: modern-go-application.service
        dest: "{{ user.home }}/.config/systemd/user/{{ mga_service_name }}.service"
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
        mode: 0600

-
    name: Enable systemd service
    systemd:
        name: "{{ mga_service_name }}"
        enabled: true
        scope: user
    become: true
    become_user: "{{ user.name }}"
    environment:
        XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
