name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Download dependencies
        run: go mod download
        env:
          GOPROXY: https://proxy.golang.org

      - name: Build
        run: make build
        env:
          VERBOSE: 1

      - name: Unit tests
        run: make test
        env:
          VERBOSE: 1

      - name: Integration tests
        run: make test-integration
        env:
          VERBOSE: 1

      - name: Lint
        run: make lint

  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Build image
        run: docker build --build-arg GOPROXY=https://proxy.golang.org -t docker.pkg.github.com/${GITHUB_REPOSITORY}/${{ github.event.repository.name }}:${GITHUB_SHA:0:7} .

      - name: Tag image
        run: docker tag docker.pkg.github.com/${GITHUB_REPOSITORY}/${{ github.event.repository.name }}:${GITHUB_SHA:0:7} docker.pkg.github.com/${GITHUB_REPOSITORY}/${{ github.event.repository.name }}:${GITHUB_REF#"refs/heads/"}
        if: github.event_name == 'push'

      - name: Tag latest image
        run: docker tag docker.pkg.github.com/${GITHUB_REPOSITORY}/${{ github.event.repository.name }}:${GITHUB_SHA:0:7} docker.pkg.github.com/${GITHUB_REPOSITORY}/${{ github.event.repository.name }}:latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'

      - name: Log in to registry
        run: echo ${{ secrets.DOCKER_GITHUB_PASSWORD }} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
        if: github.event_name == 'push'

      - name: Push image
        run: docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/${{ github.event.repository.name }}
        if: github.event_name == 'push'
